server:
  port: 8590
  servlet:
    context-path: /chat-gpt

info:
  app:
    name: ${spring.application.name}
    description: chat-gpt微服务
  author: Alexon

spring:
  #项目名字
  application:
    name: chat-gpt
  # 数据源
  datasource:
    name: oredr-ds
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/order?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&serverTimezone=GMT%2B8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:  #druid相关配置
      filters: stat #监控统计拦截的filters
      initial-size: 1  #配置初始化大小/最小/最大
      min-idle: 1
      max-active: 20
      max-wait: 60000 #获取连接等待超时时间
      time-between-eviction-runs-millis: 60000  #间隔多久进行一次检测，检测需要关闭的空闲连接
      min-evictable-idle-time-millis: 300000  #一个连接在池中最小生存的时间
      validation-query: SELECT 'x'
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      max-pool-prepared-statement-per-connection-size: 20
  # redis
  redis: # redis配置
    host: 127.0.0.1
    port: 6379
    # password: xlt
    database: 0
    lettuce:
      pool:
        max-active: 8 # 连接池最大连接数 默认8 ，负数表示没有限制
        max-wait: -1 # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
        max-idle: 8 # 连接池中的最大空闲连接 默认8
        min-idle: 0 # 连接池中的最小空闲连接 默认0


# chat GPT API Token,获取地址：https://platform.openai.com/account/api-keys
chatgpt:
  token: "sk-xxxx"

#jwt
jwt:
  expiration: 1800 # 令牌过期时间 此处单位秒
  skip:
    permission: false # 权限检查跳过
  token:
    secret: 12345abcd # token加密密钥

# Springboot Admin监控暴露信息
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

# mybatis配置
mybatis:
  config-location: classpath:config/mybatis-config.xml
  mapper-locations: classpath*:mapper/*.xml
  type-aliases-package: com.xlt.model

# 权限扫描基础路径
base:
  service:
    path: com.xlt.controller

### log4j2配置
logging:
  config: classpath:log/log4j2.xml

# http pool配置
http_pool:
  max_total: 200
  default_max_per_route: 100
  connect_timeout: 5000
  connection_request_timeout: 1000
  socket_timeout: 65000
  validate_after_inactivity: 2000


