server:
  port: 8099

# 单机eureka
eureka:
  instance:
#    hostname: localhost  # eureka服务端的实例名称
    hostname: eureka-server  # eureka服务端的实例名称
  client:
    registerWithEureka: false # false表示自己不需要向注册中心注册自己
    fetchRegistry: false # false声明自己就是注册中心。我的职责就是维护服务实例，并不需要去检索服务
    serviceUrl:
      #  http://192.168.26.128:8098/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS
